repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: go-mod-tidy

  - repo: https://github.com/golangci/golangci-lint
    rev: v2.4.0
    hooks:
      - id: golangci-lint

  - repo: local
    hooks:
      - id: go-vet
        name: go vet
        entry: go vet ./...
        language: system
        pass_filenames: false
        files: '\.go$'
        stages: [pre-commit, pre-push]

      - id: go-test
        name: go test
        entry: go test -short ./...
        language: system
        pass_filenames: false
        files: '\.go$'
        stages: [pre-commit, pre-push]

      - id: go-build
        name: go build
        entry: go build ./cmd/vizvault
        language: system
        pass_filenames: false
        files: '\.go$'
        stages: [pre-commit, pre-push]

      - id: gosec
        name: gosec
        entry: gosec -fmt json -out /dev/null ./...
        language: system
        pass_filenames: false
        files: '\.go$'
        stages: [pre-push]

      - id: govulncheck
        name: govulncheck
        entry: govulncheck ./...
        language: system
        pass_filenames: false
        files: '(go\.mod|go\.sum|\.go)$'
        stages: [pre-push]

default_stages: [pre-commit, pre-push]
fail_fast: false
minimum_pre_commit_version: '3.0.0'
