name: Merge Queue

on:
  merge_group:
    types: [checks_requested]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.merge_group.head_sha }}
  cancel-in-progress: true

jobs:
  quick-check:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25'
        cache: true
        cache-dependency-path: go.sum

    - name: Fast checks
      run: |
        go mod verify
        go vet ./...
        go test -short ./...

    - name: Build check
      run: go build ./cmd/vizvault
