name: Test Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'

    - name: Build
      run: |
        echo "Building VizVault..."
        CGO_ENABLED=0 go build -buildvcs=false -o bin/vizvault ./cmd/vizvault
        echo "Build complete!"

    - name: Test binary
      run: |
        ./bin/vizvault version

    - name: Build Docker image
      run: |
        docker build -t vizvault:test .
